### ISSUE TITLE
Where is the Output displayed?

### ISSUE THREAD

**Issue by sanaafhn** [sumtype/CIEDE2000#1]
The program is executing successfully but where is the output being displayed?

**Comment by sumtype** [comment]
There isn't any output.  The script contains functions, but doesn't run any of them when executed.

If you want to call the CIEDE2000 function to see it's output for two input colors you could add something like this to the bottom of the file, then execute it:

`print(ciede2000(rgb2lab((255,255,255)), rgb2lab((0,0,0))))`
