### ISSUE TITLE
values wrong

### ISSUE THREAD

**Issue by nschloe** [sumtype/CIEDE2000#2]
The values this script produces are (slightly) off. Compare with the reference values at http://www2.ece.rochester.edu/~gsharma/ciede2000/. [This Python script](https://github.com/lovro-i/CIEDE2000/blob/master/ciede2000.py) does the right thing.

**Comment by sumtype** [comment]
Thanks @nschloe, I've updated it according to the excel implementation provided here:
http://www2.ece.rochester.edu/~gsharma/ciede2000

This version passes the test cases here:
http://www2.ece.rochester.edu/~gsharma/ciede2000/dataNprograms/ciede2000testdata.txt

see https://github.com/sumtype/CIEDE2000/blob/master/tests.py
